name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # oder master, je nachdem welchen Branch-Namen du verwendest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: |
          export NUXT_APP_BASE_URL="/"
          npx nuxt build --preset github_pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .output/public
          force_orphan: true